### ISSUE TITLE
API to expose participant CSV urls

### ISSUE THREAD

**Issue by webbo89** [cybsafe/phishtray#132]
List all participants.

#Acceptance Criteria

A new url that corresponds to a exercise, will list ALL participants, which should present a URL, which allows you to download the CSV for that particular participant (In a separate ticket)

**Comment by fericsepi** [comment]
To list exercises:
![image](https://user-images.githubusercontent.com/20440288/47087374-bbb1bf80-d213-11e8-9aa5-ccb9cc4d40a5.png)
Following up on the link `exerciseReportsUrl`:
![image](https://user-images.githubusercontent.com/20440288/47087410-d4ba7080-d213-11e8-8b42-16b7672e1270.png)

Closing - been resolved as part of #125
