### ISSUE TITLE
[FE] CSS Styling Required on the Welcome Page

### ISSUE THREAD

**Issue by webbo89** [cybsafe/phishtray#140]
## Acceptance Criteria

* Paragraph styling
* Bullet points
* Good line height 
* Title line height spacing

**Comment by oluomoniyi** [comment]
Files Modal - file preview needs to show larger / 100% in the window. https://github.com/cybsafe/phishtray/issues/146

**Comment by oluomoniyi** [comment]
Improve the styling on the Replies. 
No need to be yellow.
Padding is very wrong
https://github.com/cybsafe/phishtray/issues/142

**Comment by oluomoniyi** [comment]
![image](https://user-images.githubusercontent.com/1480266/47075812-2f909f80-d1f5-11e8-99df-68b25c8f99a2.png)

**Comment by oluomoniyi** [comment]
![image](https://user-images.githubusercontent.com/1480266/47079344-125fcf00-d1fd-11e8-9ab8-0a7dde193eb9.png)
