### ISSUE TITLE
[Bug] The experiment count needs to start when the exercise begins, not when users are reading the instructions

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#182]
It currently sets off as soon as they get the link. Instructions are long to read and they cut off experiment time, where emails are specifically set to appear at certain times.

**Comment by ceaia-tiberiu** [comment]
I can't reproduce this issue. The timer in code starts when you click on "Click here to start the E-tray"  and not on "Continue" ( the first button )
Maybe when you test it, there was an already exercise in progress and you didn't click Exit ( that button clears the timer ) and you started another link / exercise and the timer remained started from the previous exercise

**Comment by ceaia-tiberiu** [comment]
I've added a reset counter when you enter the first time on the exercise link. 
In this way, the starting counter will start every time from 0, and will not keep the data from the other exercise. In this way, we will know for sure that the counter is starting properly.
