### ISSUE TITLE
Number Question Required Not Working

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#188]
For questions in the welcome form that use the `Number` question type, there is a default value of 0. So even though the question is set to `required`, the user can still skip the question due to the field being populated by the default number.

https://github.com/cybsafe/phishtray/blob/master/frontend/src/pages/Exercise/index.js#L208-L218

**Comment by bendiggle** [comment]
I need to find a better solution for this. Carbon has a `NumberInput` that seems a bit rubbish.

**Comment by bendiggle** [comment]
PR is here https://github.com/cybsafe/phishtray/pull/337

**Comment by bendiggle** [comment]
PR is here https://github.com/cybsafe/phishtray/pull/337
