### ISSUE TITLE
Fixed date displayed on the platform, instead of current date.

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#202]
Modify the Email to either use the time and date set or default to the current date and time.

<img width="1680" alt="Screenshot 2019-09-19 at 09 19 03" src="https://user-images.githubusercontent.com/11047071/65226322-8f0ac580-dabe-11e9-8a79-7237daea9ab9.png">

Use property moment to display the date and time of the email from the api response. `dateReceived` in `threadProperties`

![Screenshot 2019-10-29 at 17 14 03](https://user-images.githubusercontent.com/11047071/67791588-9b941d80-fa6f-11e9-82ae-009c2e81a077.png)

**Comment by bendiggle** [comment]
<img width="1680" alt="Screenshot 2019-09-19 at 09 19 03" src="https://user-images.githubusercontent.com/11047071/65226322-8f0ac580-dabe-11e9-8a79-7237daea9ab9.png">

**Comment by fericsepi** [comment]
Add a new field to email properties for date, when date is provided  default reveal time to 0

**Comment by fericsepi** [comment]
BE issue is at #317

**Comment by bendiggle** [comment]
PR Merged: https://github.com/cybsafe/phishtray/pull/329
