### ISSUE TITLE
Introduce Tenancy to Phishtray

### ISSUE THREAD

**Issue by webbo89** [cybsafe/phishtray#212]
Phishtray now has a requirement to support multiple organisations - I.e. for single instance multi-tenancy.

- [x] Introduce the Organisations, with fields for name
- [x] Associate staff users to an organisation
- [x] Associate participants to an organisation
- [x] Restrict Django Administration to only show what your organisation owns (except for super users)

**Comment by celopacob** [comment]
https://github.com/cybsafe/phishtray/pull/227
