### ISSUE TITLE
[User Story 2.3] As an administrator I would like to setup my own unique links so that I can further segment experiments to run my trials more efficiently by creating projects.

### ISSUE THREAD

**Issue by webbo89** [cybsafe/phishtray#217]
Experiments have unique ID's

/welcome/fa45afe4fa4f5445ae45a45e45
(relates to experiment 4)

We'd like to create a trial variation URL so we can perform segmentation on our experiments.

/welcome/fa45afe4fa4f5445ae45a45e45/5
(relates to experiment 4) and trial 5

Requires a new model for Trials
- accepts a stringname
- unique number
- associates to experiment

- [x] Produce the Trial Model
- [x] Add to the django administration
- [x] Adjust the /init/ endpoint to accept the *optional* trial ID and persist it to the participant data

https://www.emtray.com/api/v1/exercises/c266f00c-e42a-4d19-bff7-460310c5aa34/init/{{trial id}}

**Comment by celopacob** [comment]
https://github.com/cybsafe/phishtray/pull/237

**Comment by fericsepi** [comment]
This feat has been dealt with in #251 #240 #270 
Admins can now create trials that are interconnected, can create exercise copies.
Each trial will have their own unique ID that can be used as before without changing the FE.
