### ISSUE TITLE
[BUG] Email Attachments

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#219]
- There is a weird bug where, if you click on an attachment in the email, it will take you to a blank `/files` page with no files table and not showing you the attachment
- However, if you go to the `/files` page first and then go to your inbox and click on the attachment, it will work.

![Screenshot 2019-10-28 at 09 59 45](https://user-images.githubusercontent.com/11047071/67685338-cc4f5680-f98c-11e9-82ae-876dd0838449.png)

**WHAT IT LOOKS LIKE:** 
<img width="1680" alt="Screenshot 2019-10-28 at 14 17 47" src="https://user-images.githubusercontent.com/11047071/67686114-1be25200-f98e-11e9-88a9-2f405a2ca709.png">

**WHAT IT SHOULD LOOK LIKE:**
<img width="1680" alt="Screenshot 2019-10-28 at 14 16 37" src="https://user-images.githubusercontent.com/11047071/67686141-269ce700-f98e-11e9-96ab-faa962adf023.png">

**Comment by fericsepi** [comment]
I can confirm that the BE is sending this info.
Just talked to Ben n ow and it seems that the FE is missing some logic to make files appear in File manager "dynamically".

Example payload:
![image](https://user-images.githubusercontent.com/20440288/67410387-f206e500-f5b3-11e9-9433-75ad88bf54a8.png)

Assigning this to Ben so he can add some specs.

**Comment by bendiggle** [comment]
PR Merged: https://github.com/cybsafe/phishtray/pull/325
