### ISSUE TITLE
[User stories 1.4 & 2.1] Add field in Email so administrators can write end-of-exercise feedback to the participants

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#220]
![Screenshot 2019-09-20 at 15 24 55](https://user-images.githubusercontent.com/43407551/65334718-e8581f00-dbba-11e9-9af9-5a685d40f1d7.png)

This is to provide feedback for each individual phishing email at the end of the experiment debrief. Each phishing email should have a field where administrators can explain the main threats involved,etc. 

User stories:

2.1. As an administrator I can provide text based feedback against a phishing email so that it can be presented to participants (See 1.4).

1.4. As a participant when I am notified about the phishing email, I am presented specific text about the phishing risks contained within the email.

- [ ] E.g. fieldname phishing_explained which is text field which must support a paragraph.
- [ ] Add to the serializer

**Comment by asgharsir** [comment]
I think, I heard to add that field to admin site also. Right?

**Comment by bendiggle** [comment]
> I think, I heard to add that field to admin site also. Right?

@asgharsir Yeah only add the field to the admin site. Frontend will come later on

**Comment by asgharsir** [comment]
PR #228
