### ISSUE TITLE
[User Stories 2.2] Add per email phishing action field to experiment debrief

### ISSUE THREAD

**Issue by webbo89** [cybsafe/phishtray#221]
Updates:
Example fields to be added to each phishing email in the response:
```
{
  ...,
  "participantBehaviour": "Negative / Positive / Neutral",
  "participantActions": [
    {"actionType": "email_opened", "time_delta": 1234},
    {"actionType": "email_reported", "time_delta": 2345}
  ]
}
```
- [x] add the participantBehaviour
- [x] add participantActions (list)
-----
Blocked by #223 

2.2. As an administrator I can provide risk scores against a phishing email so that it can be presented to participants (See 1.4).

Goal: Show the list of all actions recorded against the phishing email, and highlight the top action

![image](https://user-images.githubusercontent.com/1236578/65334946-5b619580-dbbb-11e9-8ffa-0e71c3ce40d4.png)

Example of the output field per phishing email:

```
{"participantReaction": {"Message": "Downloaded Content", "Result": "Negative"}
{"participantReactionList": [ "Reaction": "Downloaded Content", "Created":"2019-09-10 12:12:12",  "Reaction": "Downloaded Content", "Created":"2019-09-10 12:12:12"]
}

```
- [n/a] Include the participantReaction in the per phishing debrief
- [n/a] Include the participantReactionList

**Comment by asgharsir** [comment]
PR #245

**Comment by asgharsir** [comment]
PR #256
