### ISSUE TITLE
Supports [User Story 2.3]

### ISSUE THREAD

**Issue by webbo89** [cybsafe/phishtray#225]
1. Extend the participant model to accept a trial ID
Extend the /init/ API to accept the Trial id via GET.

E.g. /welcome/{exercise-url}/{trial-id}

Depends on this:
https://github.com/cybsafe/phishtray/issues/217

**Comment by celopacob** [comment]
Hi folks, This is a frontend task, no? Once the 'phishtray.local:3000/welcome/:experiment_id:' ends up calling the ':experiment_id:/init/', and, in case of a trial, call ':experiment_id:/init/:trial_id:', which is already been covered by https://github.com/cybsafe/phishtray/issues/217

**Comment by bendiggle** [comment]
@celopacob Frontend ticket lives here https://github.com/cybsafe/phishtray/issues/231.
This was to just change the init api endpoint to allow the trial_id which you've covered already so you can just move this along with #217 😄

**Comment by celopacob** [comment]
So nice!

**Comment by fericsepi** [comment]
Won't need these updates - trials are exercises as well so the current logic should still work.
