### ISSUE TITLE
[User Story 2.3] Exercise trials route

### ISSUE THREAD

**Issue by bendiggle** [cybsafe/phishtray#231]
The welcome route currently only supports an exercise id. It needs to also support a trial id.

It should be able to handle an exerciseUuid on it's own and with a trialUuid.

Change `/welcome/:exerciseUuid` to `/welcome/:exerciseUuid/:trialUuid?`.

Will also need to change the `init` endpoint in `exerciseActions` to support the trialUuid and again exerciseUuid on it's own

Links to Backend ticket here: https://github.com/cybsafe/phishtray/issues/217

**Comment by fericsepi** [comment]
Won't need to append trial ids anymore - trials are exercises as well so the current logic should still work with trials (once the BE changes are rolled out).
