### ISSUE TITLE
[User Stories 2.6] Copy Exercise

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#240]
### Story:
Admins should be able to copy exercises so it's easier to create a new experiment and to iterate on one further especially when the changes introduced to the new version are subtle.

#### `Exercise`
- [x] admins can see and copy both `public` and `private` exercises (that belong to the given organisation)
⚠️ The new copy should be `private` (populate the organisation field)
- [x] add a ForeignKey field `copied_from` to `Exercise` to track the source exercise
- [x] add a custom button `Copy Exercise` to the Exercise Edit form so admins can make copies of an Exercise
- [x] admins can copy an `Exercise`, when this happens the new field `copied_from` should contain the ID of the original Exercise

**Comment by celopacob** [comment]
Yet the same PR! :)
https://github.com/cybsafe/phishtray/pull/237

**Comment by celopacob** [comment]
https://github.com/cybsafe/phishtray/pull/273

**Comment by fericsepi** [comment]
Merged #273
