### ISSUE TITLE
[User Stories 2.4] Trial Stats (CSV generator)

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#241]
### Story:
As an administrator I would like to see a list of participants (in a CSV) so that I can evaluate the results of each sub-experiment (trial), with some key highlights:
Admins should have the option to either download the CSV including all trials or select a specific trial.

#### Example CSV:
![image](https://user-images.githubusercontent.com/20440288/68205350-fa9ee880-ffc1-11e9-9afe-9dce4f134f4a.png)

##### 2.4.0 Exercise details
- [x] title of exercise - column `exercise_title`
- [x] trial version of the given exercise - column `trial_version`
- [x] how many participants have attempted the exercise in total - column `participant_count`

##### 2.4.1 Emails opened
- [x] count of phishing emails opened - column `emails_opened`
- [x] count of all emails that the participant has opened - column `phishing_emails_opened`

##### 2.4.2 Phishing interaction behaviour (sum of participants for positive + negative events)
- [x] ➕ reported - column `pos_reported`
- [x] ➕ deleted - column `pos_deleted`
- [x] ➖ clicked link - column `neg_clicked_link`
- [x] ➖ entered details(on web page) - column `neg_entered_detail`
- [x] ➖ replied to an email (event fired when the Reply button is clicked at the top of the email)  - column `neg_replied_to_phishing_email`
- [x] ➖ downloaded attachment - column `neg_opened_attachment`

##### 2.4.3. Tracking participants and training data
- [x] ~~if training link is NOT provided populate `'n/a'` in the field~~
**Updates from Carla on 2019-11-22:** 
**>>** populate `n/a` when debrief is disabled for the given exercise
- [x] ~~if training link provided count how many participants clicked the link~~
**Updates from Carla on 2019-11-22:** 
**>>** when debrief is enabled for the exercise count how many participants clicked the training link
  Action type for opening training link at the end of an exercise is `training_link_clicked`
  - bool - did the participant click on the training link (if training link avail)

**Comment by fericsepi** [comment]
Dependent on #251

**Comment by celopacob** [comment]
PR for review: https://github.com/cybsafe/phishtray/pull/374

**Comment by celopacob** [comment]
When the exercise debrief is ticked, csv will bring the training link clicked count;
When the exercise debrief is NOT ticked, csv will bring 'N.A.'

**Comment by fericsepi** [comment]
Updated the description based on Carla's comments.

**Comment by fericsepi** [comment]
#374 was merged
