### ISSUE TITLE
Exercise Trials - nested filtering for django admin

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#242]
### Story:
In Participants we can currently filter the participant list by exercise. However, with introducing the trials, there will be multiple trials per exercise. The participants of these multiple trials/exercise should still belong to the same exercise. 

Therefore we need to display a dynamic filter in Participants. 

If an administrator filters by an Exercise that has trials, the trial IDs should display underneath as filters, so the admin can get a list of participants from each individual trial. 

![image](https://user-images.githubusercontent.com/43407551/66035517-32b69580-e503-11e9-9ced-352b439bba49.png)

### Acceptance Criteria:
- [x] add a secondary filter (trial filter) which allows admins to select a trial version for the selected exercise (`initial_exercise`). For example for an exercise with 2 trial variations the list of options would be: `1`, `2`, `3`
- [x] selecting an exercise should refresh the secondary filter with available trial versions for the selected exercise
- [x] if nothing is selected in the trial filter then participants from all trials should be displayed
- [x] if the admin selects a trial version only participants of that trial should be on display in the table
- [x] (for avoidance of doubt) generating the CSV in this view should reflect the participant selection on display

### Bonus (if time allows)
- [x] admins should not be able to add new `Participants` in this view - the only way should be through the FE welcome page

**Comment by celopacob** [comment]
https://github.com/cybsafe/phishtray/tree/feature/242-Participant-Nested-Filtering

**Comment by celopacob** [comment]
PR: https://github.com/cybsafe/phishtray/pull/328

**Comment by fericsepi** [comment]
Merged #328 - closing Issue
