### ISSUE TITLE
[SNACK] Exercise help_text

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#244]
Improve help text at Exercise
![image](https://user-images.githubusercontent.com/20440288/66055767-efbde780-e52d-11e9-9774-92f86ae0b1a4.png)

Acceptance Criteria:
- [x] provide help text for `training_link` - it should read `Defaults to a training URI provided by Cybsafe.`
- [x] Adjust help text for `debrief` - it should read `Should participants receive a phishing debrief at the end of the exercise?`

**Comment by asgharsir** [comment]
PR #249
