### ISSUE TITLE
[Debrief] Phishing Email Info

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#248]
Create a page to display the phishing emails that the user was presented with.

Using `phishingEmails` from the api response, loop over the emails and display the following info:
- Header 
- Description
- Email Info
- Participant Actions
- Particpant Behaviour

Keep the same URL all emails and just toggle the state to display the correct email.

**Header**
- Display Header with number email is in the list e.g. `Phishing Email 1` -> `Phishing Email 2`

**Description**
- In api response field is called `phishingExplained` (You can add it to the email in admin to test)

**Email Info**
- Display To, From, Subject, Body
- from -> `fromAddress `, subject -> `subject`, body -> `content`

**Participant Actions**
- api response field is `participantActions`
- Show the overall action first (This will be the next action after email_opened -> `participantActions[1]`)
- Show more link that displays the entire list of actions and time in the exercise that the action happened 

**Participant Behaviour**
- api response field is `participantBehaviour`
- Display `negative` or `positive` text. If `neutral` don't display anything

**Next/Previous**
- Display Next Button if there is an email after the current one in the list
- Display Previous Button if there is an email before the current one in the list
- At the last email, instead of next button have a continue button which takes the participant to the next page(Page is a different ticket)

Example of API Response:
<img width="856" alt="Screenshot 2019-10-15 at 18 06 52" src="https://user-images.githubusercontent.com/11047071/66853231-abdbd100-ef76-11e9-864a-4814ce0f9295.png">

To have an idea of what a page should look like: 
![image](https://user-images.githubusercontent.com/43407551/66118481-5d215500-e5ce-11e9-800f-b285c4519412.png)

Designs for inspiration (but please use carbon) https://invis.io/KRU7OOD76T9#/383663937_Feedback_Page_Email_2

**Comment by bendiggle** [comment]
PR Merged: https://github.com/cybsafe/phishtray/pull/304
