### ISSUE TITLE
[Debrief] Training Page

### ISSUE THREAD

**Issue by czz22** [cybsafe/phishtray#250]
Create Page in Debrief which provides the participant with a link to training material

**Header**
- Page same Header `Thanks for taking the exercise` as other debrief pages.

**Button**
- In api response there is a field called `trainingLink`. This determines the link of the button.
- If `trainingLink !== ''` -> then the link = `trainingLink`
- else link = `https://app.cybsafe.com` <-- the new page is being created for us so for now just use this url and we will change it later on  
- Button text `Take me to free resource` with icon (https://fontawesome.com/icons/external-link-alt?style=solid)
- Link opens new tab in window
- Use `logAction` function to track whether users have clicked the training button

**Image**
- Image link: `https://cybsafe-resources.s3-eu-west-1.amazonaws.com/image13.png`

![image](https://user-images.githubusercontent.com/43407551/66118960-8d1d2800-e5cf-11e9-8a6a-0ce8c18b5924.png)

**Comment by bendiggle** [comment]
PR Merged: https://github.com/cybsafe/phishtray/pull/302
