### ISSUE TITLE
Remove Password Field from My Payment Account

### ISSUE THREAD

**Issue by bendiggle** [cybsafe/phishtray#265]
Remove the Password section of My Payment as the web page doesn't have a password field.
Change `username` to be `Email Address`

<img width="1680" alt="Screenshot 2019-10-07 at 17 42 03" src="https://user-images.githubusercontent.com/11047071/66331221-ed8ecb00-e929-11e9-9c3e-8db395417faa.png">

**Comment by fericsepi** [comment]
merged #277
