### ISSUE TITLE
UnitTests for OrganizationQuerySet

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#268]
### Story:
As per coverage report test coverage for `OrganizationQuerySet` can be improved.

-----

### Acceptance Criteria:
Please add tests in the following file `participant/tests/test_querysets.py`:
- [x] add a `TestCase` for `OrganizationQuerySet`
- [x] add a test to cover when `user` is `None`
(QuerySet should be empty)
- [x] add a test to cover when `user` is **not** a `User` instance
(QuerySet should be empty)
- [x] add a test to cover when `user` is a `superuser`
(QuerySet should contain all Organizations)
- [x] add a test to cover when user is **not** a superuser and has no organisation attached
(QuerySet should be empty)
- [x] add a test to cover when user is **not** a superuser and has an organisation linked to it
(QuerySet should contain 1 Organization, the one that the user's linked to)

**Comment by asgharsir** [comment]
PR 268
