### ISSUE TITLE
UnitTests for ParticipantQuerySet

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#269]
### Story:
As per coverage report test coverage for `ParticipantQuerySet` can be improved.

-----

### Acceptance Criteria:
Please add tests in the following file `participant/tests/test_querysets.py`:
- [x] add a new `TestCase` for `ParticipantQuerySet`
- [x] add a test to cover when `user` is `None`
(QuerySet should be empty)
- [x] add a test to cover when `user` is **not** a `User` instance
(QuerySet should be empty)
- [x] add a test to cover when `user` is a `superuser`
(QuerySet should contain all Participants)
- [x] add a test to cover when user is **not** a superuser and has no organisation attached
(QuerySet should be empty)
- [x] add a test to cover when user is **not** a superuser and has an organisation linked to it
(QuerySet should contain a subset of Participants that belong to the same Organization as the user)

**Comment by asgharsir** [comment]
PR #274

**Comment by fericsepi** [comment]
#274 has been merged
