### ISSUE TITLE
Upcycling ExerciseWebPage

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#278]
### Story:
Admins should be able to add custom web pages to the platform which can be loaded as and when required.
The project already has a model called `ExerciseWebPages` that we can upcycle (since it's not currently used for anything).

#### Tidy up `ExerciseWebPages` class
- [x] rename class to `ExerciseWebPage`
- [x] rename field `subject` to `title`
- [x] remove `verbose_name_plural`

#### Updates to `ExerciseWebPage`
- [x] make `url` unique
- [x] introduce a new attribute `PAGE_TYPES` within the class with 1 choice `REGULAR`
_(there will be more types in the future i.e. info or warning)_
- [x] update choices for `type` to `PAGE_TYPES` and default it to `REGULAR`

#### Tests
- [x] add a new test case called `ExerciseWebPageModelTestCase` to `exercise/test_models.py`
- [x] introduce a test to check that 2 `ExerciseWebPage` cannot have the same url

**Comment by fericsepi** [comment]
Re `type` - don't think we have anything stored in that table so there shouldn't be an issue.
Re `PAGE_TYPE` - don't mind if you extract it but then please add them to `exercise/constants.py` pls.

**Comment by asgharsir** [comment]
PR #279

**Comment by fericsepi** [comment]
the PR needs review not the Issue :)

**Comment by fericsepi** [comment]
#279 has been merged
