### ISSUE TITLE
Remove ExerciseURL

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#282]
#### Story:
As of today model `ExerciseURL` is not being used and might be confusing to admins as well as developers what it is used for. Let's remove it for now, it would be easy to reintroduce it should we need to in the future.

#### Acceptance Criteria:
- [x]  remove class `ExerciseURL`

**Comment by asgharsir** [comment]
PR #283

**Comment by fericsepi** [comment]
Notes: #283 has introduced a migration clash which got resolved by #286
Closing since #286 was merged.
