### ISSUE TITLE
Serializer for ExerciseEmailProperties

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#289]
### Story:
Phishtray APIs should support to send the new properties introduced by Issue #281 

#### Serializer for ExerciseWebPage
- [x] create a new serializer called `ExerciseWebPageSerializer` which should return the following fields: `title, url, type, content`

#### Serializer for ExerciseEmailProperties
- [x] create a new serialiser called `ExerciseEmailPropertiesSerializer` for fields
    - [x] `reveal_time` - add to fields
    - [x] `web_page` - use ExerciseWebPageSerializer here
    - [x] `intercept_exercise` - add it simply to fields
    - [x] `release_codes` - SerializerMethodField to return a list of release codes

#### Update ThreadSerializer
- [x] add a new field called `thread_properties` - use a `SerializerMethodField`
- [x] use ExerciseEmailPropertiesSerializer within `get_thread_properties`

#### Tests - TBC

**Comment by asgharsir** [comment]
PR #293

**Comment by fericsepi** [comment]
Merged #293
