### ISSUE TITLE
Move phishingExplained to participant-scores endpoint

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#297]
### Story:
As an administrator I can provide text based feedback against a phishing email so that it can be presented to participants at the end of the exercise.

### Acceptance Criteria:
- [ ] the values should only be exposed as part of the `participant-scores` endpoint.
    - [ ] remove `phishing_explained` from `ThreadSerializer`
    - [ ] add `phishing_explained` to `participant-scores` endpoint

**Comment by asgharsir** [comment]
PR #300

**Comment by fericsepi** [comment]
Merged #300
