### ISSUE TITLE
Add sent date to email properties

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#317]
### Story:
This is the BE ticket for #202 

### Acceptance Criteria
- [x] add a datetime field to ExerciseEmailProperties called `date_received` (this field can be left blank and is not required)
- [x] when `date_received` is set, `reveal_time` should be set to `0` automatically
- [x] add `date_received` to `ExerciseEmailPropertiesSerializer`

### Tests
- [x] test that reveal_time changes from `None` to `0` when `date_received` is set
- [x] test that reveal_time remains `0` when `date_received` is set even if the user tries to set a different reveal_time
- [x] test that reveal_time changes from `>0` to `0` when `date_received` is set
- [x] test that reveal_time remains `None` when `date_received` is not set

**Comment by asgharsir** [comment]
PR #319

**Comment by fericsepi** [comment]
#319 has been merged
