### ISSUE TITLE
Remove To/From image upload

### ISSUE THREAD

**Issue by bendiggle** [cybsafe/phishtray#340]
- The researchers don't use the functionality to add an image to the To and From user for the emails.
- The frontend has removed this functionality and replaced it with the users initials.
- So now this functionality can be removed from the backend

<img width="620" alt="Screenshot 2019-11-07 at 08 55 26" src="https://user-images.githubusercontent.com/11047071/68374350-a9673400-013c-11ea-8efd-451025373a02.png">

**Comment by asgharsir** [comment]
PR #343

**Comment by fericsepi** [comment]
merged #343
