### ISSUE TITLE
[EmailDebrief] Positive/Negative Actions

### ISSUE THREAD

**Issue by bendiggle** [cybsafe/phishtray#400]
Currently in the debrief for a phishing email, we get a list of actions performed on that email and then an overall behaviour for that email (positive/negative).

The backend will now also provide the FE with the action_id for each action. Then `participantBehaviour` will provide the FE with the behaviour (POSITIVE/NEGATIVE) and the action id that gave the email that overall behaviour

You will need to:
- Use the actionId to get the action from the list of actions
- Then display the positive/negative message based on that action
- In the list of actions, make that action bold, so the participant know which action gave them tha behaviour

**Comment by fericsepi** [comment]
Prereq Issue #407

**Comment by fericsepi** [comment]
#407 is now complete

**Comment by bendiggle** [comment]
PR https://github.com/cybsafe/phishtray/pull/420
