### ISSUE TITLE
[EmailDebrief] Extend participant_behaviour with action_id

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#407]
### Story
It would be very helpful to participants to know which of their actions has defined the behaviour for any given (phishing) email during the debrief.
To allow this, the FE would need to know the action_id along with the behaviour outcome.

### Acceptance Criteria
Update `phishing_email_behaviour_and_actions` to return a tuple `(DICT, LIST)`.
As per the docstring, this method currently returns `(STRING, LIST) - returns a tuple of participant behaviour and actions`
- [x] update `participant_behaviour` within `phishing_email_behaviour_and_actions` to return a dictionary which resembles as follow:
    ```python
    pb = {
        behaviour: ParticipantBehaviour.NEUTRAL
        action_id: <UUID of action that defined behaviour above>
    }
    ```
- [x] tests to verify the above contract and that the correct `action_id` is being returned

**Comment by asgharsir** [comment]
PR #413
