### ISSUE TITLE
[CREST] add column in csv to track when they've entered code

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#408]
### Story
As a follow up of #241, please extend the CSV report so researchers can track how many participants entered the release code if and when they're blocked during the exercise.

For ref the current CSV looks like this:
![image](https://user-images.githubusercontent.com/20440288/69435880-47abea00-0d38-11ea-8111-17ace3c92c95.png)

### Acceptance Criteria
- [x] add new field `code_entered`
this field should sum up how many codes were entered in total during the exercise
this can be calculated as follows `code_correct` + `code_incorrect`
- [x] add new field `code_correct`
event name is `training_release_code_correct`
this field should sum up how many participants have entered the code correctly during the exercise
- [x] add new field `code_skipped` - 🏗FE to implement action call #414 
event name `training_release_code_skipped`
this field should sum up how many times the internal browser window with release code prompt was closed without an attempt to enter the code
- [x] add new field `code_incorrect` - 🏗FE to implement action call #414 
event name `training_release_code_incorrect`
this field should sum up how many times participants tried to submit an incorrect code

For ref please see the updated CSV below (with the new fields highlighted in red):
![image](https://user-images.githubusercontent.com/20440288/69436737-dec57180-0d39-11ea-8e9c-b9722e42de04.png)

**Comment by fericsepi** [comment]
Updated description

**Comment by celopacob** [comment]
PR: https://github.com/cybsafe/phishtray/pull/421
