### ISSUE TITLE
Copy Emails, Files and Demographics when copying a public exercise as an admin

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#424]
### Story
When copying a public exercise as an admin all necessary data that is related to the exercise should be made available for the given organisation otherwise the exercise copy will not be functional when it is tweaked/iterated further.

### Acceptance Criteria
During copying an exercise
- [x] copy the linked **demographics** info to the admin's organisation
- [x] copy the linked **files** to the admin's organisation
- [x] copy the linked **emails** _(inc. attachments and replies)_ to the admin's organisation
- [x] copy the linked **email properties** _(inc. web page and release codes)_ to the admin's organisation
TBC - will the web page and release codes need to be copied?

**Comment by asgharsir** [comment]
As Feri is already adding Emails, I have added Demographics and Files. PR #425

**Comment by fericsepi** [comment]
Tested and released.
