### ISSUE TITLE
BE Exercise API review.

### ISSUE THREAD

**Issue by DanielGeoffreyHodgkins** [cybsafe/phishtray#52]
To integrate React & Django, a review of the endpoint is required.

Endpoints:
* `api/v1/exercise/` - list
* `api/v1/exercise/<ID>/` - details
* `api/v1/email/` - list
* `api/v1/email/<ID>/` - details
* `api/v1/thread/` - list
* `api/v1/thread/<ID>/` - details

Sign off would be:

[ ] Only logged in admins should be able to access list view
[ ] UUIDs so users cannot easily guess IDs and browse the public API 
[ ] Sensible naming conventions
[ ] Endpoint flexible for further development

**Comment by fericsepi** [comment]
#58

**Comment by fericsepi** [comment]
#58 Merged - closing
