### ISSUE TITLE
BE Django API to allow React Replacement of http://phishtray.cybsafedev.com:8000/exercise/WLE/profile

### ISSUE THREAD

**Issue by fericsepi** [cybsafe/phishtray#54]
## Acceptance Criteria:
1. [x] add `field_type` (number/string eval) and `required` to the model _(so forms can implement field validation)_
2.  [x] add linked questions to the exercise endpoint - see example below:
```
"profile_form":  [  
    {
        "id": "uuid-123", "question": "How old are you", "question_type": 1, "required": false
    },
    {
        "id": "uuid-432", "question": "What is your main browser", "question_type": 2, "required": true
    }
]
```
3. [x] add endpoint _(POST only)_ to be able to submit question/answers prior to starting the exercise
Example **POST** payload:
```
"profile_form":  [  
    {
        "id": "uuid-123", "value": "Some answer"
    },
    {
        "id": "uuid-432", "value": "Another answer"
    }
]
```

**Comment by webbo89** [comment]
Slight change on this ticket - can this data object be included as part of the detail API, so it can all be provided in one call. 

Data will look something like this:

profile_form
       [  
        { key: 432, label: "How old are you", type: number/string },
       ]

POST endpoint can remain separate.
