### ISSUE TITLE
FE 6.1. As a participant I can open the Web browser and recognise common features of a web browser such as url bar and security lock so I can simulate a typical web experience.

### ISSUE THREAD

**Issue by iozzyi** [cybsafe/phishtray#67]

**Comment by oluomoniyi** [comment]
![screen shot 2018-09-20 at 09 55 35](https://user-images.githubusercontent.com/1480266/45807526-89b44880-bcbb-11e8-92f4-ffe8f62bce1c.png)

**Comment by oluomoniyi** [comment]
![screen shot 2018-09-20 at 09 57 27](https://user-images.githubusercontent.com/1480266/45807554-9cc71880-bcbb-11e8-8f5e-5e5b1510a65c.png)
